pages:
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm install
    - npm run build
    - mv --backup=existing dist/* public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master